@base=http://localhost:5124

### Dingtalk Webhook
POST {{base}}/dingtalk
Content-Type: application/json

{
    "alerts": [
        {
            "status": "resolved",
            "labels": {
                "alertname": "机器宕机监测",
                "instance": "10.180.48.2",
                "job": "node_exporter",
                "serverity": "warning"
            },
            "annotations": {
                "description": "机器:10.180.48.2 所属 job:node_exporter 宕机超过1分钟，请检查！",
                "summary": "机器发生宕机"
            },
            "startsAt": "2024-01-10T11:59:09.775Z",
            "endsAt": "2024-01-10T13:00:00Z",
            "fingerprint": "02f13394997e5211",
            "count": 1
        }
    ]
}

### Lark Webhook
POST {{base}}/lark
Content-Type: application/json

{
    "alerts": [
        {
            "status": "resolved",
            "labels": {
                "alertname": "机器宕机监测",
                "instance": "10.180.48.2",
                "host": "node-01",
                "serverity": "warning"
            },
            "annotations": {
                "description": "机器:10.180.48.2 所属 job:node_exporter 宕机超过1分钟，请检查！",
                "summary": "机器发生宕机"
            },
            "startsAt": "2024-01-10T11:59:09.775Z",
            "endsAt": "2024-01-10T13:00:00Z",
            "fingerprint": "02f13394997e5211",
            "count": 1
        }
    ]
}
