@base=http://localhost:5124

### Dingtalk Webhook
POST {{base}}/dingtalk/{{DINGTALK_WEBHOOK_TOKEN}}
Content-Type: application/json

{
    "alerts": [
        {
            "status": "resolved",
            "labels": {
                "alertname": "机器宕机监测",
                "instance": "10.110.0.3",
                "host": "node-02",
                "severity": "warning"
            },
            "annotations": {
                "description": "node-02（10.110.0.3），宕机超过1分钟，请检查！",
                "summary": "机器发生宕机"
            },
            "startsAt": "2024-01-10T11:59:09.775Z",
            "endsAt": "2024-01-10T13:00:00Z",
            "fingerprint": "02f13394997e5211"
        }
    ]
}

### Lark Webhook
POST {{base}}/lark/{{LARK_WEBHOOK_TOKEN}}
Content-Type: application/json

{
    "alerts": [
        {
            "status": "firing",
            "labels": {
                "alertname": "机器宕机监测",
                "instance": "10.110.0.2",
                "host": "node-01",
                "project": "demo",
                "severity": "warning",
                "env": "production"
            },
            "annotations": {
                "description": "node-01（10.110.0.2），宕机超过1分钟，请检查！",
                "summary": "机器发生宕机"
            },
            "startsAt": "2024-01-10T11:59:09.775Z",
            "endsAt": "2024-01-10T13:00:00Z",
            "fingerprint": "02f13394997e5211"
        },
        {
            "status": "resolved",
            "labels": {
                "alertname": "机器宕机监测",
                "instance": "10.110.0.3",
                "host": "node-02",
                "severity": "warning",
                "env": "production"
            },
            "annotations": {
                "description": "node-02（10.110.0.3），宕机超过1分钟，请检查！",
                "summary": "机器发生宕机"
            },
            "startsAt": "2024-01-10T11:59:09.775Z",
            "endsAt": "2024-01-10T13:00:00Z",
            "fingerprint": "02f13394997e5211"
        }
    ]
}
